# -*- coding: utf-8 -*-
# @Author: Diogo Telheiro do Nascimento
# @Date:   2022-03-15 20:18:55
# @Last Modified by:   Diogo Telheiro do Nascimento
# @Last Modified time: 2022-03-20 14:29:18
services:
  some-service:
    build:
      context: ./Dockerfile
      dockerfile: ${DOCKERFILE_PROD}
    image: ${IMAGE_NAME}:latest
    ports:
      - "5000:5000"
    working_dir: ${WORKDIR}
